name: Artifact Demo
on: 
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: src-folder
          path: |
            src
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: src-folder
      - name: Output Content
        run: ls
