name: Matrix Demo
on:
  push:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-last, windows-last, macos-last]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4