name: Security
on: 
  #push:

#Injection Attacks
#Unknown Actions
#Mitigate Permissons

permissions:
  issues: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Issue Name
        env:
          user-input: ${{ github.ref_name }}
        run: echo ${{ env.user-input }}
